"""Add SensorReadingPublic model

Revision ID: 155953105f7e
Revises: 5abfbdde8f8a
Create Date: 2024-05-26 11:15:17.975813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '155953105f7e'
down_revision = '5abfbdde8f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
