"""Rename to soil_moisture

Revision ID: cfc1ba3d3d79
Revises: 155953105f7e
Create Date: 2024-06-06 12:12:53.148780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfc1ba3d3d79'
down_revision = '155953105f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorreading', sa.Column('soil_moisture', sa.Float(), nullable=False))
    op.drop_column('sensorreading', 'soil_humidity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorreading', sa.Column('soil_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('sensorreading', 'soil_moisture')
    # ### end Alembic commands ###
