"""Add aggregation tables

Revision ID: e4ad3a2e95dc
Revises: cfc1ba3d3d79
Create Date: 2024-07-31 19:14:55.552110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e4ad3a2e95dc'
down_revision = 'cfc1ba3d3d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailysensorreading',
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('air_humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthlysensorreading',
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('air_humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeklysensorreading',
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('air_humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeklysensorreading')
    op.drop_table('monthlysensorreading')
    op.drop_table('dailysensorreading')
    # ### end Alembic commands ###
